appearance_thresh: 0.4
fuse_score: true
gmc_method: sparseOptFlow
match_thresh: 0.99
new_track_thresh: 0.3
proximity_thresh: 0.5
track_buffer: 20
track_high_thresh: 0.25
track_low_thresh: 0.1
tracker_type: botsort
with_reid: true
